version: '3.8'

services:
  app:
    image: ghcr.io/wforeros1/taller3_devops/python-app:latest 
    ports:
      - "8000:8000"
    networks:
      - monitoring-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
    restart: unless-stopped

networks:
  monitoring-net:

volumes:
  grafana-storage: