name: Desplegar Servicios de Monitoreo

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a EC2 y desplegar monitoreo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd Taller3_devops
            git pull
            sudo /usr/local/bin/docker-compose -f monitoring/docker-compose.monitoring.yml up -d prometheus grafana