name: Desplegar Servicios de Monitoreo

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a EC2 y desplegar monitoreo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd Taller3_devops 
            git pull
            
            echo ${{ secrets.GH_PAT }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

            sudo /usr/local/bin/docker-compose pull

            sudo /usr/local/bin/docker-compose up -d prometheus grafana
