name: Desplegar Servicios de Monitoreo

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a EC2 y desplegar monitoreo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd "/home/ec2-user/app" 

            sudo /usr/local/bin/docker-compose up -d prometheus 
            sudo /usr/local/bin/docker-compose up -d grafana
